version: '3.4'

services:
  data-binding:
    image: data-binding
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8085
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]